version: "2"

services:
  test:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes_from:
      - cache
    networks:
      - test-network
    mem_limit: 128000000
    container_name: "todobackend-test"
    environment:
      - DJANGO_SETTINGS_MODULE
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - TEST_OUTPUT_DIR
    depends_on:
      - db

  cache:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - /tmp/cache:/cache
    entrypoint: "true"
    container_name: "cache"

  db:
    image: mysql:5.6
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - test-network
    container_name: "db"


networks:
  test-network:
    driver: bridge
